apiVersion: apps/v1
kind: Deployment
metadata:
  name: CTest-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: CTest-ui
  template:
    metadata:
      labels:
        app: CTest-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-CTest-demo:0.2
        name: CTest-ui
        ports:
        - containerPort: 80
